### ISSUE TITLE
Hagni40 dataset

### ISSUE THREAD

**Issue by dakomura** [hacylu/Hagnifinder#1]
Hello there,

I'm interested in working with the Hagni40 dataset. 
Could you please provide me with a link or instructions on how to access this dataset?

Thank you very much for your help.

Best regards,

**Comment by hacylu** [comment]
For sure. Will provide you with the access to the Hagni40 in a couple of
days.
Remind us if not send you the link. Thanks.

**Comment by dakomura** [comment]
Thank you so much for your quick response! 
I appreciate your assistance and look forward to working with the dataset soon.

**Comment by hacylu** [comment]
No problem.
Hongtai(cc him in this email thread) is trying to upload the dataset into
BaiduNetdrive. It is about 30GBytes in total :)

**Comment by hacylu** [comment]
Hi Daisuke,
please find the Hagni40 dataset via below webdrive link. Thanks.

https://pan.baidu.com/s/1nLcqALwgGY0MPLbVzAOLtw?pwd=vhic

**Comment by dakomura** [comment]
Hi,
I couldn't read Chinese in the link, but I successfully downloaded the files with the help of my Chinese friend!
Thank you!

**Comment by hacylu** [comment]
Glad to hear it!
