### ISSUE TITLE
Hagni40.txt

### ISSUE THREAD

**Issue by dakomura** [hacylu/Hagnifinder#2]
Hi Hongtai,

I'm trying to reproduce the result in your paper, but Hagni40.zip you gave me does not contain `Hagni40.txt`, which is necessary to run `train.py`.

Could you please provide me with the file?

Thank you very much for your help.

Best regards,
Daisuke

**Comment by hacylu** [comment]
Sorry for the late reply. You can run src/set_dataset_info.py to load the dataset information and get the Hagni40 .txt, which is also mentioned in the README.

**Comment by dakomura** [comment]
Sorry for the late reply. I was able to generate the Hagni40.txt file as you mentioned. Thank you very much!
